// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBuZymX2QEfW1lXBwnHDihxFANUcgajYow',
//     appId: '1:260866481377:web:25072b066bd1575064aba0',
//     messagingSenderId: '260866481377',
//     projectId: 'leader-app-104a2',
//     authDomain: 'leader-app-104a2.firebaseapp.com',
//     storageBucket: 'leader-app-104a2.appspot.com',
//     measurementId: 'G-1SGZQKZD0H',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAMpSxkosqOfDyxTi8UNlpNXkwLZyBimq0',
//     appId: '1:260866481377:android:5e82b061b8a907b164aba0',
//     messagingSenderId: '260866481377',
//     projectId: 'leader-app-104a2',
//     storageBucket: 'leader-app-104a2.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAg0L3mHx3D4-W2D35wn_FF-6KQWDUiU_Y',
//     appId: '1:260866481377:ios:4ddb77a4f66c44ae64aba0',
//     messagingSenderId: '260866481377',
//     projectId: 'leader-app-104a2',
//     storageBucket: 'leader-app-104a2.appspot.com',
//     iosClientId:
//         '260866481377-9361gccaso5ikp5mj1q9ndm9m6l7vm7h.apps.googleusercontent.com',
//     iosBundleId: 'vn.com.hodicosmetic.mobile',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAg0L3mHx3D4-W2D35wn_FF-6KQWDUiU_Y',
//     appId: '1:260866481377:ios:936e0768ab16face64aba0',
//     messagingSenderId: '260866481377',
//     projectId: 'leader-app-104a2',
//     storageBucket: 'leader-app-104a2.appspot.com',
//     iosClientId:
//         '260866481377-77miagjv27ve580m1v9m78fjhrg2qjer.apps.googleusercontent.com',
//     iosBundleId: 'com.example.leaderApp',
//   );
// }
